#!/usr/bin/env bash
#displays bad luck on 4th iteration, goodluck on 5th, Best School on 8th
i=0
good_luck="good luck"
bad_luck="bad luck"
best_school="Best School"
while [ "$i" -lt 10 ]
do
	if [ "$i" -eq 3 ]; then
		echo "$bad_luck"
	elif [ "$i" -eq 7 ]; then
		echo "$good_luck"
	else
		echo "$best_school"
	fi
	((i++))
done
