#!/usr/bin/env bash
#check if school exist
dev="school"
if [ -e "$dev" ]
then 
	echo "school file exists"
	if [ -s "$dev" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$dev" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
